# Specify the base image
FROM node:20.10.0-slim AS build


# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .



# build dependencies
RUN npm run build



# Production stage
FROM nginx:stable-alpine AS production


COPY deploy/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8000

