version: "3.6"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECT=mongodb://mongo:27017/mydatabase
    env_file : .env
  mongo:
    image: mongo
    ports:
      - 27017:27017
